lib/stackunderflow_web/router.ex
defmodule StackunderflowWeb.Router do
  use StackunderflowWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StackunderflowWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/questions", QuestionController do
      scope "/answers" do
        resources "/", AnswerController, only: [:create, :update, :delete]
        put "/:id/accecpt", AnswerController, :accept_answer
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", StackunderflowWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: StackunderflowWeb.Telemetry
    end
  end
end

lib/stackunderflow/questions/answer.ex
defmodule Stackunderflow.Questions.Answer do
  use Ecto.Schema
  import Ecto.Changeset

  schema "answers" do
    field :body, :string
    belongs_to :question, Stackunderflow.Questions.Question

    timestamps()
  end

  @doc false
  def changeset(answer, attrs) do
    answer
    |> cast(attrs, [:body])
    |> validate_required([:body])
  end
end

lib/stackunderflow_web/controllers/answer_controller.ex
defmodule StackunderflowWeb.AnswerController do
  use StackunderflowWeb, :controller

  alias Stackunderflow.Questions
  alias Stackunderflow.Questions.{Question, Answer}

  plug :scrub_params, "answer" when action in [:create, :update]

  def create(conn, %{"answer" => answer_params, "question_id" => question_id}) do
    question = Questions.get_question!(question_id)

    changeset =
      question
      |> Ecto.build_assoc(:answers)
      |> Questions.change_answer(answer_params)

    case Stackunderflow.Repo.insert(changeset) do
      {:ok, _answer} ->
        conn
        |> put_flash(:info, "Answer saved successfully")
        |> redirect(to: Routes.question_path(conn, :show, question))

      {:error, changeset} ->
        render(conn, StackunderflowWeb.QuestionView, "show.html",
          question: question,
          answer_changeset: changeset
        )
    end
  end

  def accept_answer(conn, %{"id" => answer_id, "question_id" => question_id}) do
    with %Question{} = question <- Questions.get_question!(question_id),
         %Answer{} = answer <- Questions.get_answer!(answer_id) do
      Questions.update_question(question, %{accepted_answer: Map.from_struct(answer)})

      conn
      |> put_flash(:info, "Answer accepted")
      |> redirect(to: Routes.question_path(conn, :show, question))
    else
      _ ->
        conn
        |> put_flash(:error, "Could not set answer as accepted")
        |> redirect(to: Routes.question_path(conn, :show, question_id))
    end
  end
end

lib/stackunderflow_web/views/answer_view.ex
defmodule StackunderflowWeb.AnswerView do
  use StackunderflowWeb, :view
end

lib/stackunderflow_web/templates/answer/edit.html.eex
<h1>Edit Answer</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.answer_path(@conn, :update, @answer)) %>

<span><%= link "Back", to: Routes.answer_path(@conn, :index) %></span>

lib/stackunderflow_web/templates/answer/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :body, "Your Answer" %>
  <%= text_input f, :body %>
  <%= error_tag f, :body %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

lib/stackunderflow_web/templates/answer/index.html.eex
<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for answer <- @answers do %>
    <tr>
      <td><%= answer.body %></td>

      <td>
        <span><%= link "Show", to: Routes.answer_path(@conn, :show, answer) %></span>
        <span><%= link "Edit", to: Routes.answer_path(@conn, :edit, answer) %></span>
        <span><%= link "Delete", to: Routes.answer_path(@conn, :delete, answer), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Answer", to: Routes.answer_path(@conn, :new) %></span>

lib/stackunderflow_web/templates/answer/new.html.eex
<h1>New Answer</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.answer_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.answer_path(@conn, :index) %></span>

lib/stackunderflow_web/templates/answer/show.html.eex
<h1>Show Answer</h1>

<ul>

  <li>
    <strong>Body:</strong>
    <%= @answer.body %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.answer_path(@conn, :edit, @answer) %></span>
<span><%= link "Back", to: Routes.answer_path(@conn, :index) %></span>