lib/stackunderflow_web/router.ex
defmodule StackunderflowWeb.Router do
  use StackunderflowWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StackunderflowWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/questions", QuestionController do
      scope "/answers" do
        resources "/", AnswerController, only: [:create, :update, :delete]
        put "/:id/accecpt", AnswerController, :accept_answer
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", StackunderflowWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: StackunderflowWeb.Telemetry
    end
  end
end

lib/stackunderflow/questions.ex
defmodule Stackunderflow.Questions do
  @moduledoc """
  The Questions context.
  """

  import Ecto.Query, warn: false
  alias Stackunderflow.Repo

  alias Stackunderflow.Questions.Question

  @doc """
  Returns the list of questions.

  ## Examples

      iex> list_questions()
      [%Question{}, ...]

  """
  def list_questions do
    Repo.all(Question)
    |> Repo.preload([:answers, :accepted_answer])
  end

  @doc """
  Gets a single question.

  Raises `Ecto.NoResultsError` if the Question does not exist.

  ## Examples

      iex> get_question!(123)
      %Question{}

      iex> get_question!(456)
      ** (Ecto.NoResultsError)

  """
  def get_question!(id), do: Repo.get!(Question, id) |> Repo.preload([:answers, :accepted_answer])

  @doc """
  Creates a question.

  ## Examples

      iex> create_question(%{field: value})
      {:ok, %Question{}}

      iex> create_question(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_question(attrs \\ %{}) do
    %Question{}
    |> Question.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a question.

  ## Examples

      iex> update_question(question, %{field: new_value})
      {:ok, %Question{}}

      iex> update_question(question, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_question(%Question{} = question, attrs) do
    question
    |> Question.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a question.

  ## Examples

      iex> delete_question(question)
      {:ok, %Question{}}

      iex> delete_question(question)
      {:error, %Ecto.Changeset{}}

  """
  def delete_question(%Question{} = question) do
    Repo.delete(question)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking question changes.

  ## Examples

      iex> change_question(question)
      %Ecto.Changeset{data: %Question{}}

  """
  def change_question(%Question{} = question, attrs \\ %{}) do
    Question.changeset(question, attrs)
  end

  alias Stackunderflow.Questions.Answer

  @doc """
  Returns the list of answers.

  ## Examples

      iex> list_answers()
      [%Answer{}, ...]

  """
  def list_answers do
    Repo.all(Answer)
  end

  @doc """
  Gets a single answer.

  Raises `Ecto.NoResultsError` if the Answer does not exist.

  ## Examples

      iex> get_answer!(123)
      %Answer{}

      iex> get_answer!(456)
      ** (Ecto.NoResultsError)

  """
  def get_answer!(id), do: Repo.get!(Answer, id)

  @doc """
  Creates a answer.

  ## Examples

      iex> create_answer(%{field: value})
      {:ok, %Answer{}}

      iex> create_answer(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_answer(attrs \\ %{}) do
    %Answer{}
    |> Answer.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a answer.

  ## Examples

      iex> update_answer(answer, %{field: new_value})
      {:ok, %Answer{}}

      iex> update_answer(answer, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_answer(%Answer{} = answer, attrs) do
    answer
    |> Answer.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a answer.

  ## Examples

      iex> delete_answer(answer)
      {:ok, %Answer{}}

      iex> delete_answer(answer)
      {:error, %Ecto.Changeset{}}

  """
  def delete_answer(%Answer{} = answer) do
    Repo.delete(answer)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking answer changes.

  ## Examples

      iex> change_answer(answer)
      %Ecto.Changeset{data: %Answer{}}

  """
  def change_answer(%Answer{} = answer, attrs \\ %{}) do
    Answer.changeset(answer, attrs)
  end
end

lib/stackunderflow/questions/answer.ex
defmodule Stackunderflow.Questions.Answer do
  use Ecto.Schema
  import Ecto.Changeset

  schema "answers" do
    field :body, :string
    belongs_to :question, Stackunderflow.Questions.Question

    timestamps()
  end

  @doc false
  def changeset(answer, attrs) do
    answer
    |> cast(attrs, [:body])
    |> validate_required([:body])
  end
end

lib/stackunderflow/questions/question.ex
defmodule Stackunderflow.Questions.Question do
  use Ecto.Schema
  import Ecto.Changeset

  schema "questions" do
    field :body, :string
    field :title, :string
    has_many :answers, Stackunderflow.Questions.Answer
    has_one :accepted_answer, Stackunderflow.Questions.Answer, on_replace: :nilify

    timestamps()
  end

  @doc false
  def changeset(question, attrs) do
    question
    |> cast(attrs, [:title, :body])
    |> cast_assoc(:accepted_answer)
    |> validate_required([:title, :body])
  end
end

lib/stackunderflow_web/controllers/question_controller.ex
defmodule StackunderflowWeb.QuestionController do
  use StackunderflowWeb, :controller

  alias Stackunderflow.Questions
  alias Stackunderflow.Questions.Question
  alias Stackunderflow.Questions.Answer

  def index(conn, _params) do
    questions = Questions.list_questions()
    render(conn, "index.html", questions: questions)
  end

  def new(conn, _params) do
    changeset = Questions.change_question(%Question{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"question" => question_params}) do
    case Questions.create_question(question_params) do
      {:ok, question} ->
        conn
        |> put_flash(:info, "Question created successfully.")
        |> redirect(to: Routes.question_path(conn, :show, question))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    question = Questions.get_question!(id)

    answer_changeset =
      question
      |> Ecto.build_assoc(:answers)
      |> Questions.change_answer()

    render(conn, "show.html", question: question, answer_changeset: answer_changeset)
  end

  def edit(conn, %{"id" => id}) do
    question = Questions.get_question!(id)
    changeset = Questions.change_question(question)
    render(conn, "edit.html", question: question, changeset: changeset)
  end

  def update(conn, %{"id" => id, "question" => question_params}) do
    question = Questions.get_question!(id)

    case Questions.update_question(question, question_params) do
      {:ok, question} ->
        conn
        |> put_flash(:info, "Question updated successfully.")
        |> redirect(to: Routes.question_path(conn, :show, question))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", question: question, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    question = Questions.get_question!(id)
    {:ok, _question} = Questions.delete_question(question)

    conn
    |> put_flash(:info, "Question deleted successfully.")
    |> redirect(to: Routes.question_path(conn, :index))
  end
end

lib/stackunderflow_web/views/question_view.ex
defmodule StackunderflowWeb.QuestionView do
  use StackunderflowWeb, :view
end

lib/stackunderflow_web/templates/question/edit.html.eex
<h1>Edit Question</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.question_path(@conn, :update, @question)) %>

<span><%= link "Back", to: Routes.question_path(@conn, :index) %></span>

lib/stackunderflow_web/templates/question/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= text_input f, :body %>
  <%= error_tag f, :body %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/stackunderflow_web/templates/question/index.html.eex
<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for question <- @questions do %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.body %></td>

      <td>
        <span><%= link "Show", to: Routes.question_path(@conn, :show, question) %></span>
        <span><%= link "Edit", to: Routes.question_path(@conn, :edit, question) %></span>
        <span><%= link "Delete", to: Routes.question_path(@conn, :delete, question), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Question", to: Routes.question_path(@conn, :new) %></span>

lib/stackunderflow_web/templates/question/new.html.eex
<h1>New Question</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.question_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.question_path(@conn, :index) %></span>

lib/stackunderflow_web/templates/question/show.html.eex
<span><%= link "Edit", to: Routes.question_path(@conn, :edit, @question) %></span>
<span><%= link "Back", to: Routes.question_path(@conn, :index) %></span>

<h1><%= @question.title %></h1>
<p><%= @question.body %>

<%= render StackunderflowWeb.AnswerView, "form.html", changeset: @answer_changeset, action: Routes.question_answer_path(@conn, :create, @question) %>

<%= if @question.accepted_answer do %>
<h3>Accepted Answer</h3>

<div style="background: #cfc; padding: 18px">
  <%= @question.accepted_answer.body %>
</div>
<% end %>

<hr />

<h3>Answers</h3>

<%= for answer <- Enum.reverse(@question.answers) do %>
  <div style="display: flex; justify-content: space-between; background: #eee; padding: 18px; margin: 6px">
  <%= answer.body %>
  <%= form_for @conn, Routes.question_answer_path(@conn, :accept_answer, @question, answer), [method: :put], fn f -> %>
    <%= submit "Accept Answer" %>
  <% end %>

</div>
<% end %>